export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const BRANDS_FETCH_START = "BRANDS_FETCH_START";
export const BRANDS_FETCH_SUCCESS = "BRANDS_FETCH_SUCCESS";
export const BRANDS_FETCH_FAIL = "BRANDS_FETCH_FAIL";
export const PHONES_FETCH_START = "PHONES_FETCH_START";
export const PHONES_FETCH_SUCCESS = "PHONES_FETCH_SUCCESS";
export const PHONES_FETCH_FAIL = "PHONES_FETCH_FAIL";
